#!/usr/bin/python3

from sys import argv
from src.display_usage import display_usage
from src.check_arg import check_arg


def main() -> int:
    if len(argv) == 2 and argv[1] == "-h":
        return display_usage()
    return check_arg(argv[1:])


if __name__ == "__main__":
    exit(main())
