#!/usr/bin/python3

from sys import argv
from src.display_usage import display_usage


def main() -> int:
    if len(argv) == 2 and argv[1] == "-h":
        return display_usage()
    return 0


if __name__ == "__main__":
    exit(main())
