#!/usr/bin/python3

from sys import argv
from src.display_usage import display_usage
from src.error_handling import check_error


def main() -> int:
    if len(argv) == 2 and argv[1] == "-h":
        return display_usage()
    check_error(argv[1:])

    return 0


if __name__ == "__main__":
    exit(main())
